### ISSUE TITLE
todo list

### ISSUE THREAD

**Issue by RainbowAsteroids** [RainbowAsteroids/DogeBalanceChecker#6]
- [ ] test and push 1.6

- [ ] make deleteAddress command

- [ ] add more configurable settings
